### ISSUE TITLE
DateTime conversion

### ISSUE THREAD

**Issue by chuck-john** [rails-sqlserver/activerecord-sqlserver-adapter#652]
We are in the process of converting our application from PostgreSQL to SQL Server. We have the application running so far without any issues. However, our test suite won't run because the Rails fixtures do not load. We are receiving the following error:

![tiny tds date error](https://user-images.githubusercontent.com/1545623/41926087-f4830118-7933-11e8-89bc-6600b07983bd.png)

This error repeats for every table insert from the fixtures containing a `DateTime` field. Our fixture for the error above is:

```yaml
announcement:
  user: administrator
  body: <%= Faker::Lorem.paragraph %>
  effective_at: <%= 10.days.ago %>
  expires_at: <%= 10.days.from_now %>
```

What's strange is we can insert records with `DateTime` fields from our web application but the fixtures fail. Here's the SQL for the successful insert via the web app:

```sql
EXEC sp_executesql N'INSERT INTO [announcements] ([created_at], [updated_at], [user_id], [body], [effective_at], [expires_at]) OUTPUT INSERTED.[id] VALUES (@0, @1, @2, @3, @4, @5)', N'@0 datetime, @1 datetime, @2 bigint, @3 nvarchar(max), @4 datetime, @5 datetime', @0 = '06-26-2018 16:24:21.256', @1 = '06-26-2018 16:24:21.256', @2 = 1, @3 = N'fewfew', @4 = '06-26-2018 05:00:00.0', @5 = '06-30-2018 05:45:00.0'
```

`ActiveSupport::TimeWithZone` seems to be part of the problem; using `10.days.ago.to_datetime` fixes the test. Is this expected behavior or should we be able to use `TimeWithZone` natively?
